
from dataclasses import dataclass

@dataclass
class WatchItem:
    ticker:str
    priority:str
    trigger:str
    note:str

class WatchlistEngine:
    def build(self,candidates:list[dict]):
        items=[]
        for c in candidates:
            s=int(c.get("score",0))
            if s>=85:
                p="High"; trig="Watch for pullback"
            elif s>=70:
                p="Medium"; trig="Wait for confirmation"
            else:
                p="Low"; trig="Monitor only"
            items.append(WatchItem(c["ticker"],p,trig,"Generated by Samantha"))
        return items
